### ISSUE TITLE
'random' ordering issue

### ISSUE THREAD

**Issue by dpasut** [dpasut/Top-Radio-to-spotify#3]
Fix random order issue for top songs of past week. Currently, every run reorders the songs with the same song count. Figure out a way to do some sort of seeding.

**Comment by jghjgfgh** [comment]
Switch from the playlists being views to just having them inline in the Python code. 

Then pick an interval you want the playlist to be reshuffled, write a Python function that calculates the MD5 of the `song_name + artist_name + str(int(unix_time / interval))` and returns an int. Probably only want to use the first few characters of the MD5 to get your int.

Then, inject your function into Sqlite3 (https://docs.python.org/2.7/library/sqlite3.html#sqlite3.Connection.create_function), and use that rather than `random()` for the secondary sort.

**Comment by dpasut** [comment]
done!
